services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: finstream-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: finstream-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  ollama:
    image: ollama/ollama:latest
    container_name: finstream-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  postgres:
    image: pgvector/pgvector:pg16
    container_name: finstream-postgres
    environment:
      POSTGRES_DB: finstream_vectorstore
      POSTGRES_USER: finstream_user
      POSTGRES_PASSWORD: finstream_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  neo4j:
    image: neo4j:5-community
    container_name: finstream-neo4j
    environment:
      NEO4J_AUTH: neo4j/finstream_password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
volumes:
  ollama_data:
  postgres_data:
  neo4j_data:
